spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Chat
    username: postgres
    password: Ufym->q-b-Vjyf
  flyway:
    url: jdbc:postgresql://localhost:5432/Chat
    locations: classpath:db/migration
    user: postgres
    password: Ufym->q-b-Vjyf
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

logging:
  level:
    root: DEBUG