server:
    port: 9000
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/Chatdb
        username: postgres
        password: Ufym->q-b-Vjyf
    jpa:
        hibernate:
            ddl-auto: update
client:
    id: 98c7778c-1f68-4d78-ad76-38cb4a4dca9b
    clientId: admin-client
    clientSecret: secret
    scopes: write, read, delete, all
    redirectUri: http://127.0.0.1:9000/login/oauth2/code
logging:
    level:
        root: DEBUG